<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
	  <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Application\Koncar.Interview.Server.Application\Koncar.Interview.Server.Application.csproj" />
	</ItemGroup>

</Project>
