<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Koncar.Interview.Server.Application\Koncar.Interview.Server.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\Koncar.Interview.Server.Infrastructure.Db.Postgres\Koncar.Interview.Server.Infrastructure.Db.Postgres.csproj" />
    <ProjectReference Include="..\Presentation\Koncar.Interview.Server.Presentation.Api\Koncar.Interview.Server.Presentation.Api.csproj" />
  </ItemGroup>

</Project>
