<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<OpenApiGenerateDocumentsOnBuild>false</OpenApiGenerateDocumentsOnBuild>
		<UserSecretsId>3147c0f2-46f4-4976-82e0-1bb92627ec80</UserSecretsId>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="10.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Scalar.AspNetCore" Version="2.11.10" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
		<PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
		<PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
		<PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application\Koncar.Interview.Server.Application\Koncar.Interview.Server.Application.csproj" />
		<ProjectReference Include="..\Infrastructure\Koncar.Interview.Server.Infrastructure.Db.Postgres\Koncar.Interview.Server.Infrastructure.Db.Postgres.csproj" />
		<ProjectReference Include="..\Presentation\Koncar.Interview.Server.Presentation.Api\Koncar.Interview.Server.Presentation.Api.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Logs\" />
	</ItemGroup>

</Project>
